"""add workspace soft delete

Revision ID: 27b94cd6684a
Revises: 20295738b124
Create Date: 2026-10-03 19:18:43.723102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b94cd6684a'
down_revision: Union[str, Sequence[str], None] = '20295738b124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspaces', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'deleted_by')
    op.drop_column('workspaces', 'deleted_at')
    # ### end Alembic commands ###
