[project]
name = "sprintalis-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arun" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "google-auth>=2.57.0",
    "passlib[argon2]>=1.7.4",
    "pydantic-settings>=2.15.0",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uuid-utils>=0.17.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
sprintalis-api = "sprintalis_api:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
